name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # --- NUEVO PASO: Configurar la versión de Node.js ---
      # Esto es crucial para que Angular CLI encuentre la versión de Node.js que necesita.
      - name: Set up Node.js for Angular build
        uses: actions/setup-node@v4 # Usa la versión v4 de la acción
        with:
          node-version: '20.x' # Puedes usar '20.x' o '22.x' según la versión exacta de Angular que uses.
          # El error indicaba '^20.19.0 || ^22.12.0 || >=24.0.0', así que '20.x' debería ser suficiente.
          cache: 'npm' # Usa 'npm' para caché de dependencias. Si usas yarn, cámbialo a 'yarn'.

      # Los siguientes pasos de OIDC no son directamente necesarios para el despliegue básico
      # de Static Web Apps con el token de despliegue, pero si los necesitas para otros propósitos,
      # puedes mantenerlos. Los elimino en este ejemplo simplificado para claridad.
      # - name: Install OIDC Client from Core Package
      #   run: npm install @actions/core@1.6.0 @actions/http-client
      # - name: Get Id Token
      #   uses: actions/github-script@v6
      #   id: idtoken
      #   with:
      #      script: |
      #          const coredemo = require('@actions/core')
      #          return await coredemo.getIDToken()
      #      result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_FOREST_0D8CE9C1E }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/grupoSADE" # Built app content directory - optional
          # Si no estás usando OIDC de forma específica para tu Static Web App,
          # puedes eliminar la siguiente línea para simplificar.
          # github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
          app_location: ''
          azure_static_web_apps_api_token: ''
